[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn -w 4 -b 0.0.0.0:$PORT 'travel_aigent:create_app()'"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3